/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import javax.swing.JLabel;

/**
 *
 * @author adhish
 */
public class AdminDashboardPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminDashboardPanel
     */
    public AdminDashboardPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        mainTitleJLabel = new javax.swing.JLabel();
        statsPanel = new javax.swing.JPanel();
        usersCard = new javax.swing.JPanel();
        UsersTitleJLabel = new javax.swing.JLabel();
        userCountLabel = new javax.swing.JLabel();
        sessionsCard = new javax.swing.JPanel();
        SessionsTitleJLabel = new javax.swing.JLabel();
        sessionCountLabel = new javax.swing.JLabel();
        productsCard = new javax.swing.JPanel();
        ProductsTitleJLabel = new javax.swing.JLabel();
        productCountLabel = new javax.swing.JLabel();
        paymentsCard = new javax.swing.JPanel();
        PaymentsTitleJLabel = new javax.swing.JLabel();
        paymentCountLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new java.awt.BorderLayout());

        mainPanel.setBackground(new java.awt.Color(51, 51, 51));
        mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        mainPanel.setLayout(new java.awt.BorderLayout());

        mainTitleJLabel.setBackground(new java.awt.Color(51, 51, 51));
        mainTitleJLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        mainTitleJLabel.setForeground(new java.awt.Color(255, 255, 255));
        mainTitleJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mainTitleJLabel.setText("Admin Dashboard");
        mainPanel.add(mainTitleJLabel, java.awt.BorderLayout.PAGE_START);

        statsPanel.setBackground(new java.awt.Color(51, 51, 51));
        statsPanel.setLayout(new java.awt.GridLayout(1, 4, 15, 15));

        usersCard.setBackground(new java.awt.Color(51, 51, 51));

        UsersTitleJLabel.setBackground(new java.awt.Color(51, 51, 51));
        UsersTitleJLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        UsersTitleJLabel.setForeground(new java.awt.Color(255, 255, 255));
        UsersTitleJLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        UsersTitleJLabel.setText("Users");

        userCountLabel.setBackground(new java.awt.Color(255, 255, 255));
        userCountLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        userCountLabel.setForeground(new java.awt.Color(255, 255, 255));
        userCountLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout usersCardLayout = new javax.swing.GroupLayout(usersCard);
        usersCard.setLayout(usersCardLayout);
        usersCardLayout.setHorizontalGroup(
            usersCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersCardLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(usersCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsersTitleJLabel))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        usersCardLayout.setVerticalGroup(
            usersCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersCardLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(UsersTitleJLabel)
                .addGap(18, 18, 18)
                .addComponent(userCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(477, Short.MAX_VALUE))
        );

        statsPanel.add(usersCard);

        sessionsCard.setBackground(new java.awt.Color(51, 51, 51));

        SessionsTitleJLabel.setBackground(new java.awt.Color(51, 51, 51));
        SessionsTitleJLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        SessionsTitleJLabel.setForeground(new java.awt.Color(255, 255, 255));
        SessionsTitleJLabel.setText("Sessions");

        sessionCountLabel.setBackground(new java.awt.Color(255, 255, 255));
        sessionCountLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        sessionCountLabel.setForeground(new java.awt.Color(255, 255, 255));
        sessionCountLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout sessionsCardLayout = new javax.swing.GroupLayout(sessionsCard);
        sessionsCard.setLayout(sessionsCardLayout);
        sessionsCardLayout.setHorizontalGroup(
            sessionsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sessionsCardLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(sessionsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sessionCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SessionsTitleJLabel))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        sessionsCardLayout.setVerticalGroup(
            sessionsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sessionsCardLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(SessionsTitleJLabel)
                .addGap(18, 18, 18)
                .addComponent(sessionCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(477, Short.MAX_VALUE))
        );

        statsPanel.add(sessionsCard);

        productsCard.setBackground(new java.awt.Color(51, 51, 51));

        ProductsTitleJLabel.setBackground(new java.awt.Color(51, 51, 51));
        ProductsTitleJLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        ProductsTitleJLabel.setForeground(new java.awt.Color(255, 255, 255));
        ProductsTitleJLabel.setText("Products");

        productCountLabel.setBackground(new java.awt.Color(255, 255, 255));
        productCountLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        productCountLabel.setForeground(new java.awt.Color(255, 255, 255));
        productCountLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout productsCardLayout = new javax.swing.GroupLayout(productsCard);
        productsCard.setLayout(productsCardLayout);
        productsCardLayout.setHorizontalGroup(
            productsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productsCardLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(productsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(productCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductsTitleJLabel))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        productsCardLayout.setVerticalGroup(
            productsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productsCardLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(ProductsTitleJLabel)
                .addGap(18, 18, 18)
                .addComponent(productCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(477, Short.MAX_VALUE))
        );

        statsPanel.add(productsCard);

        paymentsCard.setBackground(new java.awt.Color(51, 51, 51));

        PaymentsTitleJLabel.setBackground(new java.awt.Color(51, 51, 51));
        PaymentsTitleJLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        PaymentsTitleJLabel.setForeground(new java.awt.Color(255, 255, 255));
        PaymentsTitleJLabel.setText("Payments");

        paymentCountLabel.setBackground(new java.awt.Color(255, 255, 255));
        paymentCountLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        paymentCountLabel.setForeground(new java.awt.Color(255, 255, 255));
        paymentCountLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout paymentsCardLayout = new javax.swing.GroupLayout(paymentsCard);
        paymentsCard.setLayout(paymentsCardLayout);
        paymentsCardLayout.setHorizontalGroup(
            paymentsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentsCardLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(paymentsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(paymentCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PaymentsTitleJLabel))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        paymentsCardLayout.setVerticalGroup(
            paymentsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentsCardLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(PaymentsTitleJLabel)
                .addGap(18, 18, 18)
                .addComponent(paymentCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(477, Short.MAX_VALUE))
        );

        statsPanel.add(paymentsCard);

        mainPanel.add(statsPanel, java.awt.BorderLayout.CENTER);

        add(mainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PaymentsTitleJLabel;
    private javax.swing.JLabel ProductsTitleJLabel;
    private javax.swing.JLabel SessionsTitleJLabel;
    private javax.swing.JLabel UsersTitleJLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel mainTitleJLabel;
    private javax.swing.JLabel paymentCountLabel;
    private javax.swing.JPanel paymentsCard;
    private javax.swing.JLabel productCountLabel;
    private javax.swing.JPanel productsCard;
    private javax.swing.JLabel sessionCountLabel;
    private javax.swing.JPanel sessionsCard;
    private javax.swing.JPanel statsPanel;
    private javax.swing.JLabel userCountLabel;
    private javax.swing.JPanel usersCard;
    // End of variables declaration//GEN-END:variables

    public JLabel getPaymentCountLabel() {
        return paymentCountLabel;
    }

    public JLabel getProductCountLabel() {
        return productCountLabel;
    }

    public JLabel getSessionCountLabel() {
        return sessionCountLabel;
    }

    public JLabel getUserCountLabel() {
        return userCountLabel;
    }








}
