/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.CardLayout;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author adhish
 */
public class AdminUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminUI.class.getName());
    private CardLayout cardLayout;

    /**
     * Creates new form AdminUI
     */
    public AdminUI() {
        initComponents();
        AdminDashboardPanel dashboardPanel = new AdminDashboardPanel();
        ExerciseManagementPanel exercisePanel = new ExerciseManagementPanel();
        SessionManagementPanel sessionPanel = new SessionManagementPanel();
        FacilityManagementPanel facilityPanel = new FacilityManagementPanel();
        ProductManagementPanel productPanel = new ProductManagementPanel();
        PaymentsAdminPanel paymentsPanel = new PaymentsAdminPanel();
        ReportPanel reportPanel = new ReportPanel();
        
        contentPanel.add(dashboardPanel, "dashboard");
        contentPanel.add(exercisePanel, "exercise");
        contentPanel.add(sessionPanel, "session");
        contentPanel.add(facilityPanel, "facility");
        contentPanel.add(productPanel, "product");
        contentPanel.add(paymentsPanel,"payment");
        contentPanel.add(reportPanel, "report");
        
        cardLayout = (CardLayout) contentPanel.getLayout();
        cardLayout.show(contentPanel, "dashboard" );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        sidebarPanel = new javax.swing.JPanel();
        dashboardBTN = new javax.swing.JButton();
        exercisesBTN = new javax.swing.JButton();
        sessionsBTN = new javax.swing.JButton();
        facilitiesBTN = new javax.swing.JButton();
        productsBTN = new javax.swing.JButton();
        paymentsBTN = new javax.swing.JButton();
        reportsBTN = new javax.swing.JButton();
        logoutBTN = new javax.swing.JButton();
        rightPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        adminLabel = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GymPro - Admin");
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setResizable(false);

        sidebarPanel.setBackground(new java.awt.Color(204, 51, 0));
        sidebarPanel.setPreferredSize(new java.awt.Dimension(175, 600));
        sidebarPanel.setLayout(new java.awt.GridLayout(8, 1));

        dashboardBTN.setBackground(new java.awt.Color(204, 51, 0));
        dashboardBTN.setForeground(new java.awt.Color(255, 255, 255));
        dashboardBTN.setText("Dashboard");
        dashboardBTN.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        dashboardBTN.setBorderPainted(false);
        dashboardBTN.setPreferredSize(new java.awt.Dimension(50, 15));
        dashboardBTN.addActionListener(this::dashboardBTNActionPerformed);
        sidebarPanel.add(dashboardBTN);

        exercisesBTN.setBackground(new java.awt.Color(204, 51, 0));
        exercisesBTN.setForeground(new java.awt.Color(255, 255, 255));
        exercisesBTN.setText("Exercises");
        exercisesBTN.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        exercisesBTN.setBorderPainted(false);
        exercisesBTN.setPreferredSize(new java.awt.Dimension(50, 15));
        exercisesBTN.addActionListener(this::exercisesBTNActionPerformed);
        sidebarPanel.add(exercisesBTN);

        sessionsBTN.setBackground(new java.awt.Color(204, 51, 0));
        sessionsBTN.setForeground(new java.awt.Color(255, 255, 255));
        sessionsBTN.setText("Sessions");
        sessionsBTN.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        sessionsBTN.setBorderPainted(false);
        sessionsBTN.setPreferredSize(new java.awt.Dimension(50, 15));
        sessionsBTN.addActionListener(this::sessionsBTNActionPerformed);
        sidebarPanel.add(sessionsBTN);

        facilitiesBTN.setBackground(new java.awt.Color(204, 51, 0));
        facilitiesBTN.setForeground(new java.awt.Color(255, 255, 255));
        facilitiesBTN.setText("Facilities");
        facilitiesBTN.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        facilitiesBTN.setBorderPainted(false);
        facilitiesBTN.setPreferredSize(new java.awt.Dimension(50, 15));
        facilitiesBTN.addActionListener(this::facilitiesBTNActionPerformed);
        sidebarPanel.add(facilitiesBTN);

        productsBTN.setBackground(new java.awt.Color(204, 51, 0));
        productsBTN.setForeground(new java.awt.Color(255, 255, 255));
        productsBTN.setText("Products");
        productsBTN.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        productsBTN.setBorderPainted(false);
        productsBTN.setPreferredSize(new java.awt.Dimension(50, 15));
        productsBTN.addActionListener(this::productsBTNActionPerformed);
        sidebarPanel.add(productsBTN);

        paymentsBTN.setBackground(new java.awt.Color(204, 51, 0));
        paymentsBTN.setForeground(new java.awt.Color(255, 255, 255));
        paymentsBTN.setText("Payments");
        paymentsBTN.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        paymentsBTN.setBorderPainted(false);
        paymentsBTN.setPreferredSize(new java.awt.Dimension(50, 15));
        paymentsBTN.addActionListener(this::paymentsBTNActionPerformed);
        sidebarPanel.add(paymentsBTN);

        reportsBTN.setBackground(new java.awt.Color(204, 51, 0));
        reportsBTN.setForeground(new java.awt.Color(255, 255, 255));
        reportsBTN.setText("Reports");
        reportsBTN.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        reportsBTN.setBorderPainted(false);
        reportsBTN.setPreferredSize(new java.awt.Dimension(50, 15));
        reportsBTN.addActionListener(this::reportsBTNActionPerformed);
        sidebarPanel.add(reportsBTN);

        logoutBTN.setBackground(new java.awt.Color(204, 51, 0));
        logoutBTN.setForeground(new java.awt.Color(255, 255, 255));
        logoutBTN.setText("Logout");
        logoutBTN.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        logoutBTN.setBorderPainted(false);
        logoutBTN.setPreferredSize(new java.awt.Dimension(50, 15));
        logoutBTN.addActionListener(this::logoutBTNActionPerformed);
        sidebarPanel.add(logoutBTN);

        getContentPane().add(sidebarPanel, java.awt.BorderLayout.LINE_START);

        rightPanel.setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(0, 0, 0));
        headerPanel.setPreferredSize(new java.awt.Dimension(725, 75));

        titleLabel.setBackground(new java.awt.Color(0, 0, 0));
        titleLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Admin");
        titleLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        titleLabel.setBounds(new java.awt.Rectangle(10, 10, 10, 10));

        adminLabel.setBackground(new java.awt.Color(0, 0, 0));
        adminLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        adminLabel.setForeground(new java.awt.Color(255, 255, 255));
        adminLabel.setText("GymPro+");
        adminLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        adminLabel.setBounds(new java.awt.Rectangle(10, 10, 10, 10));

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(adminLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 461, Short.MAX_VALUE)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        rightPanel.add(headerPanel, java.awt.BorderLayout.PAGE_START);

        contentPanel.setBackground(new java.awt.Color(51, 51, 51));
        contentPanel.setLayout(new java.awt.CardLayout());
        rightPanel.add(contentPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(rightPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBTNActionPerformed
        cardLayout.show(contentPanel, "dashboard");
    }//GEN-LAST:event_dashboardBTNActionPerformed

    private void exercisesBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exercisesBTNActionPerformed
        cardLayout.show(contentPanel, "exercise");
    }//GEN-LAST:event_exercisesBTNActionPerformed

    private void sessionsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sessionsBTNActionPerformed
        cardLayout.show(contentPanel, "session");
    }//GEN-LAST:event_sessionsBTNActionPerformed

    private void facilitiesBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facilitiesBTNActionPerformed
        cardLayout.show(contentPanel, "facility");
    }//GEN-LAST:event_facilitiesBTNActionPerformed

    private void productsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsBTNActionPerformed
        cardLayout.show(contentPanel, "product");
    }//GEN-LAST:event_productsBTNActionPerformed

    private void paymentsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentsBTNActionPerformed
        cardLayout.show(contentPanel, "payment");
    }//GEN-LAST:event_paymentsBTNActionPerformed

    private void reportsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsBTNActionPerformed
        cardLayout.show(contentPanel, "report");
    }//GEN-LAST:event_reportsBTNActionPerformed

    private void logoutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTNActionPerformed
new LoginUI().setVisible(true);
    this.dispose(); 
    }//GEN-LAST:event_logoutBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminLabel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton dashboardBTN;
    private javax.swing.JButton exercisesBTN;
    private javax.swing.JButton facilitiesBTN;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logoutBTN;
    private javax.swing.JButton paymentsBTN;
    private javax.swing.JButton productsBTN;
    private javax.swing.JButton reportsBTN;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JButton sessionsBTN;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

    public JPanel getContentPanel() {
        return contentPanel;
    }

    public JButton getDashboardBTN() {
        return dashboardBTN;
    }

    public JButton getExercisesBTN() {
        return exercisesBTN;
    }

    public JButton getFacilitiesBTN() {
        return facilitiesBTN;
    }

    public JButton getLogoutBTN() {
        return logoutBTN;
    }

    public JButton getPaymentsBTN() {
        return paymentsBTN;
    }

    public JButton getProductsBTN() {
        return productsBTN;
    }

    public JButton getReportsBTN() {
        return reportsBTN;
    }

    public JButton getSessionsBTN() {
        return sessionsBTN;
    }






}
