/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.Exercise;
import Util.DataStore;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import java.util.List;





/**
 *
 * @author adhish
 */
public class ExerciseManagementPanel extends javax.swing.JPanel {
    private LinkedList<Exercise>exerciseList = new LinkedList<>();
    private TableRowSorter<DefaultTableModel> sorter;


    /**
     * Creates new form ExerciseManagementPanel
     */
    public ExerciseManagementPanel() {
        initComponents();
        loadExercisesToTable(); 
   DefaultTableModel model =
        (DefaultTableModel) exerciseTable.getModel();

sorter = new TableRowSorter<>(model);
exerciseTable.setRowSorter(sorter);    
    }
    
    private void loadExercisesToTable() {

    DefaultTableModel model =
            (DefaultTableModel) exerciseTable.getModel();

    model.setRowCount(0); // clear table first

    for (Exercise e : DataStore.exercises) {
        model.addRow(new Object[]{
            e.getName(),
            e.getMuscleGroup(),
            e.getDifficulty(),
            e.getEquipment()
        });
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        bodyPanel = new javax.swing.JPanel();
        formPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        exerciseNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        muscleGroupField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        difficultyCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        equipmentField = new javax.swing.JTextField();
        buttonPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        listPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        exerciseTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        sortByNameBtn = new javax.swing.JButton();
        sortByDifficultyBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new java.awt.BorderLayout());

        mainPanel.setBackground(new java.awt.Color(51, 51, 51));
        mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        mainPanel.setLayout(new java.awt.BorderLayout());

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Exercise Management");
        mainPanel.add(jLabel6, java.awt.BorderLayout.PAGE_START);

        bodyPanel.setBackground(new java.awt.Color(51, 51, 51));
        bodyPanel.setLayout(new java.awt.GridLayout(1, 2));

        formPanel.setBackground(new java.awt.Color(51, 51, 51));
        formPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        formPanel.setLayout(new java.awt.GridLayout(5, 2, 15, 15));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Exercise Name:");
        formPanel.add(jLabel2);

        exerciseNameField.addActionListener(this::exerciseNameFieldActionPerformed);
        formPanel.add(exerciseNameField);

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Muscle Group:");
        formPanel.add(jLabel3);

        muscleGroupField.addActionListener(this::muscleGroupFieldActionPerformed);
        formPanel.add(muscleGroupField);

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Difficulty:");
        formPanel.add(jLabel4);

        difficultyCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Easy", "Medium", "Hard", " " }));
        difficultyCombo.addActionListener(this::difficultyComboActionPerformed);
        formPanel.add(difficultyCombo);

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Equipment:");
        formPanel.add(jLabel5);

        equipmentField.addActionListener(this::equipmentFieldActionPerformed);
        formPanel.add(equipmentField);

        buttonPanel.setBackground(new java.awt.Color(51, 51, 51));
        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        jButton1.setBackground(new java.awt.Color(204, 51, 0));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        buttonPanel.add(jButton1);

        jButton2.setBackground(new java.awt.Color(204, 51, 0));
        jButton2.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(this::jButton2ActionPerformed);
        buttonPanel.add(jButton2);

        jButton3.setBackground(new java.awt.Color(204, 51, 0));
        jButton3.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Delete");
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(this::jButton3ActionPerformed);
        buttonPanel.add(jButton3);

        formPanel.add(buttonPanel);

        bodyPanel.add(formPanel);

        listPanel.setBackground(new java.awt.Color(51, 51, 51));
        listPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        listPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Exercise List:");
        listPanel.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jScrollPane3.setBackground(new java.awt.Color(51, 51, 51));

        exerciseTable.setBackground(new java.awt.Color(51, 51, 51));
        exerciseTable.setForeground(new java.awt.Color(255, 255, 255));
        exerciseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Muscle Group", "Difficulty", "Equipment"
            }
        ));
        exerciseTable.setGridColor(new java.awt.Color(255, 255, 255));
        exerciseTable.setSelectionBackground(new java.awt.Color(204, 51, 0));
        exerciseTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(exerciseTable);

        listPanel.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        sortByNameBtn.setBackground(new java.awt.Color(204, 51, 0));
        sortByNameBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        sortByNameBtn.setForeground(new java.awt.Color(255, 255, 255));
        sortByNameBtn.setText("Sort By Name");
        sortByNameBtn.setBorderPainted(false);
        sortByNameBtn.addActionListener(this::sortByNameBtnActionPerformed);
        jPanel1.add(sortByNameBtn);

        sortByDifficultyBtn.setBackground(new java.awt.Color(204, 51, 0));
        sortByDifficultyBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        sortByDifficultyBtn.setForeground(new java.awt.Color(255, 255, 255));
        sortByDifficultyBtn.setText("Sort By Difficulty");
        sortByDifficultyBtn.setBorderPainted(false);
        sortByDifficultyBtn.addActionListener(this::sortByDifficultyBtnActionPerformed);
        jPanel1.add(sortByDifficultyBtn);

        listPanel.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        bodyPanel.add(listPanel);

        mainPanel.add(bodyPanel, java.awt.BorderLayout.CENTER);

        add(mainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void exerciseNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exerciseNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exerciseNameFieldActionPerformed

    private void muscleGroupFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muscleGroupFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_muscleGroupFieldActionPerformed

    private void difficultyComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_difficultyComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_difficultyComboActionPerformed

    private void equipmentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipmentFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equipmentFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
        String name = exerciseNameField.getText().trim();
        String muscle = muscleGroupField.getText().trim();
        String difficulty = difficultyCombo.getSelectedItem().toString();
        String equipment = equipmentField.getText().trim();

        if (name.isEmpty() || muscle.isEmpty() || equipment.isEmpty()) {
            throw new IllegalArgumentException("All fields are required");
        }

        if (!name.matches("[a-zA-Z ]+")) {
            throw new IllegalArgumentException("Exercise name cannot contain numbers");
        }

        if (!muscle.matches("[a-zA-Z ]+")) {
            throw new IllegalArgumentException("Muscle group cannot contain numbers");
        }

        Exercise ex = new Exercise(name, muscle, difficulty, equipment);
        exerciseList.add(ex);

        DefaultTableModel model =
                (DefaultTableModel) exerciseTable.getModel();

        model.addRow(new Object[]{
            ex.getName(),
            ex.getMuscleGroup(),
            ex.getDifficulty(),
            ex.getEquipment()
        });

        exerciseNameField.setText("");
        muscleGroupField.setText("");
        equipmentField.setText("");

    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Input Error",
                JOptionPane.ERROR_MESSAGE);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
DefaultTableModel model = (DefaultTableModel) exerciseTable.getModel();
    int row = exerciseTable.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Select an exercise to update.");
        return;
    }

    // Read new values from input fields
    String newName = exerciseNameField.getText().trim();
    String newMuscle = muscleGroupField.getText().trim();
    String newDifficulty = difficultyCombo.getSelectedItem().toString(); // or .getSelectedItem()
    String newEquipment = equipmentField.getText().trim();

    // Basic validation
    if (newName.isEmpty() || newMuscle.isEmpty() || newDifficulty.isEmpty() || newEquipment.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields before updating.");
        return;
    }

    // Get original identifier from selected row
    String oldName = model.getValueAt(row, 0).toString();

    // Find the real object in the DataStore
    Exercise target = null;
    for (Exercise e : DataStore.exercises) {
        if (e.getName().equalsIgnoreCase(oldName)) {
            target = e;
            break;
        }
    }

    if (target == null) {
        JOptionPane.showMessageDialog(this, "Exercise not found; could not update.");
        return;
    }

    // Update object using setters
    target.setName(newName);
    target.setMuscleGroup(newMuscle);
    target.setDifficulty(newDifficulty);
    target.setEquipment(newEquipment);

    // Update table row to show new values
    model.setValueAt(target.getName(), row, 0);
    model.setValueAt(target.getMuscleGroup(), row, 1);
    model.setValueAt(target.getDifficulty(), row, 2);
    model.setValueAt(target.getEquipment(), row, 3);

    JOptionPane.showMessageDialog(this, "Exercise updated.");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  DefaultTableModel model = (DefaultTableModel) exerciseTable.getModel();
    int row = exerciseTable.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Select an exercise to delete.");
        return;
    }

    // Confirm deletion
    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete this exercise?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION
    );
    if (confirm != JOptionPane.YES_OPTION) return;

    // Grab the unique identifier from the selected row
    // (Column 0 is Exercise Name in your current table)
    String name = model.getValueAt(row, 0).toString();

    // Find matching Exercise in the DataStore list
    Exercise toRemove = null;
    for (Exercise e : DataStore.exercises) {
        if (e.getName().equalsIgnoreCase(name)) {
            toRemove = e;
            break;
        }
    }

    if (toRemove != null) {
        // Remove from data store
        DataStore.exercises.remove(toRemove);
        // Remove from table view
        model.removeRow(row);
        JOptionPane.showMessageDialog(this, "Exercise deleted.");
    } else {
        JOptionPane.showMessageDialog(this, "Exercise not found.");
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void sortByNameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByNameBtnActionPerformed
sorter.setSortKeys(
        List.of(
            new RowSorter.SortKey(
                0,              // column index for Exercise Name
                SortOrder.ASCENDING
            )
        )
    );
    }//GEN-LAST:event_sortByNameBtnActionPerformed

    private void sortByDifficultyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByDifficultyBtnActionPerformed
 sorter.setSortKeys(
        List.of(
            new RowSorter.SortKey(
                2,              // column index for Difficulty
                SortOrder.ASCENDING
            )
        )
    );
    }//GEN-LAST:event_sortByDifficultyBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JComboBox<String> difficultyCombo;
    private javax.swing.JTextField equipmentField;
    private javax.swing.JTextField exerciseNameField;
    private javax.swing.JTable exerciseTable;
    private javax.swing.JPanel formPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel listPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField muscleGroupField;
    private javax.swing.JButton sortByDifficultyBtn;
    private javax.swing.JButton sortByNameBtn;
    // End of variables declaration//GEN-END:variables
}
