/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.Facility;
import Util.DataStore;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import java.util.List;



/**
 *
 * @author adhish
 */
public class FacilityManagementPanel extends javax.swing.JPanel {
    private LinkedList<Facility> facilityList = new LinkedList<>();
    private TableRowSorter<DefaultTableModel> sorter;



    /**
     * Creates new form FacilityManagementPanel
     */
    public FacilityManagementPanel() {
        initComponents();
        loadFacilitiesToTable(); 
        DefaultTableModel model =
        (DefaultTableModel) facilityTable.getModel();

sorter = new TableRowSorter<>(model);
facilityTable.setRowSorter(sorter);
    }
    private void loadFacilitiesToTable() {

    DefaultTableModel model =
            (DefaultTableModel) facilityTable.getModel();

    model.setRowCount(0); // clear table

    for (Facility f : DataStore.facilities) {
        model.addRow(new Object[]{
            f.getFacilityName(),
            f.getFacilityType(),
            f.getAvailability(),
            f.getCapacity()
        });
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BodyPanel = new javax.swing.JPanel();
        formPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        facilityNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        facilityTypeCombo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        availabilityCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        capacityField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        facilityTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new java.awt.BorderLayout());

        mainPanel.setBackground(new java.awt.Color(51, 51, 51));
        mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        mainPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Facility Management");
        mainPanel.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        BodyPanel.setBackground(new java.awt.Color(51, 51, 51));
        BodyPanel.setLayout(new java.awt.GridLayout(1, 2, 15, 0));

        formPanel.setBackground(new java.awt.Color(51, 51, 51));
        formPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        formPanel.setLayout(new java.awt.GridLayout(5, 2, 15, 15));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Facility Name :");
        formPanel.add(jLabel2);
        formPanel.add(facilityNameField);

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Facility Type :");
        formPanel.add(jLabel3);

        facilityTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Swimming Pool", "Sauna / Steamer", "Lockers", "Cardio Floor", "Sports Center" }));
        formPanel.add(facilityTypeCombo);

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Availability :");
        formPanel.add(jLabel4);

        availabilityCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Unavailable", " " }));
        formPanel.add(availabilityCombo);

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Capacity :");
        formPanel.add(jLabel5);
        formPanel.add(capacityField);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        jButton1.setBackground(new java.awt.Color(204, 51, 0));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1);

        jButton2.setBackground(new java.awt.Color(204, 51, 0));
        jButton2.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel1.add(jButton2);

        jButton3.setBackground(new java.awt.Color(204, 51, 0));
        jButton3.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Delete");
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel1.add(jButton3);

        formPanel.add(jPanel1);

        BodyPanel.add(formPanel);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Facility List :");
        jPanel2.add(jLabel7, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));

        facilityTable.setBackground(new java.awt.Color(51, 51, 51));
        facilityTable.setForeground(new java.awt.Color(255, 255, 255));
        facilityTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Type", "Availability", "Capacity"
            }
        ));
        facilityTable.setSelectionBackground(new java.awt.Color(204, 51, 0));
        facilityTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(facilityTable);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jButton4.setBackground(new java.awt.Color(204, 51, 0));
        jButton4.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Sort By Name");
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(this::jButton4ActionPerformed);
        jPanel3.add(jButton4);

        jButton5.setBackground(new java.awt.Color(204, 51, 0));
        jButton5.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Sort By Capacity");
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(this::jButton5ActionPerformed);
        jPanel3.add(jButton5);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        BodyPanel.add(jPanel2);

        mainPanel.add(BodyPanel, java.awt.BorderLayout.CENTER);

        add(mainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 try {
        String name = facilityNameField.getText().trim();
        String type = facilityTypeCombo.getSelectedItem().toString();
        String availability = availabilityCombo.getSelectedItem().toString();
        int capacity = Integer.parseInt(capacityField.getText().trim());

        // Empty check
        if (name.isEmpty()) {
            throw new IllegalArgumentException("Facility name is required");
        }

        // Alphabet-only validation
        if (!name.matches("[a-zA-Z ]+")) {
            throw new IllegalArgumentException("Facility name cannot contain numbers");
        }

        // Capacity validation
        if (capacity <= 0) {
            throw new IllegalArgumentException("Capacity must be a positive number");
        }

        // Create object
        Facility facility = new Facility(name, type, availability, capacity);
        facilityList.add(facility);

        // Add to table
        DefaultTableModel model =
                (DefaultTableModel) facilityTable.getModel();

        model.addRow(new Object[]{
            facilityList.size(),
            facility.getFacilityName(),
            facility.getFacilityType(),
            facility.getAvailability(),
            facility.getCapacity()
        });

        // Clear form
        facilityNameField.setText("");
        capacityField.setText("");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
                "Capacity must be numeric",
                "Input Error",
                JOptionPane.ERROR_MESSAGE);

    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Input Error",
                JOptionPane.ERROR_MESSAGE);
    }    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
int row = facilityTable.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this,
                "Please select a facility to delete",
                "Delete Error",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    int modelRow = facilityTable.convertRowIndexToModel(row);

    facilityList.remove(modelRow);

    DefaultTableModel model =
            (DefaultTableModel) facilityTable.getModel();
    model.removeRow(modelRow);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try {
        int row = facilityTable.getSelectedRow();
        if (row == -1) {
            throw new IllegalArgumentException("Select a facility to update");
        }

        int modelRow = facilityTable.convertRowIndexToModel(row);

        String name = facilityNameField.getText().trim();
        String type = facilityTypeCombo.getSelectedItem().toString();
        String availability = availabilityCombo.getSelectedItem().toString();
        int capacity = Integer.parseInt(capacityField.getText().trim());

        if (!name.matches("[a-zA-Z ]+")) {
            throw new IllegalArgumentException("Invalid facility name");
        }

        if (capacity <= 0) {
            throw new IllegalArgumentException("Capacity must be positive");
        }

        // Update object
        Facility facility = facilityList.get(modelRow);
        facility.setFacilityName(name);
        facility.setFacilityType(type);
        facility.setAvailability(availability);
        facility.setCapacity(capacity);

        // Update table
        DefaultTableModel model =
                (DefaultTableModel) facilityTable.getModel();

        model.setValueAt(facility.getFacilityName(), modelRow, 1);
        model.setValueAt(facility.getFacilityType(), modelRow, 2);
        model.setValueAt(facility.getAvailability(), modelRow, 3);
        model.setValueAt(facility.getCapacity(), modelRow, 4);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
                "Capacity must be numeric",
                "Update Error",
                JOptionPane.ERROR_MESSAGE);

    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Update Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 sorter.setSortKeys(
        List.of(
            new RowSorter.SortKey(
                0,                  // Facility Name column
                SortOrder.ASCENDING
            )
        )
    );
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
sorter.setSortKeys(
        List.of(
            new RowSorter.SortKey(
                3,                  // Capacity column
                SortOrder.ASCENDING
            )
        )
    );
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BodyPanel;
    private javax.swing.JComboBox<String> availabilityCombo;
    private javax.swing.JTextField capacityField;
    private javax.swing.JTextField facilityNameField;
    private javax.swing.JTable facilityTable;
    private javax.swing.JComboBox<String> facilityTypeCombo;
    private javax.swing.JPanel formPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
