/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.Product;
import Util.DataStore;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import java.util.List;



/**
 *
 * @author adhish
 */
public class ProductManagementPanel extends javax.swing.JPanel {
    private LinkedList<Product> productList = new LinkedList<>();
    private TableRowSorter<DefaultTableModel> sorter;



    /**
     * Creates new form ProductManagementPanel
     */
    public ProductManagementPanel() {
        initComponents();
        loadProductsToTable();
        
        DefaultTableModel model =
        (DefaultTableModel) productTable.getModel();

sorter = new TableRowSorter<>(model);
productTable.setRowSorter(sorter);

    }
    private void loadProductsToTable() {

    DefaultTableModel model =
            (DefaultTableModel) productTable.getModel();

    model.setRowCount(0); // clear table

    for (Product p : DataStore.products) {
        model.addRow(new Object[]{
            p.getProductName(),
            p.getCategory(),
            p.getPrice(),
            p.getStock(),
            p.getStatus()
        });
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BodyPanel = new javax.swing.JPanel();
        formPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        productNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        categoryCombo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        priceField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        stockField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        statusCombo = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        listPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new java.awt.BorderLayout());

        mainPanel.setBackground(new java.awt.Color(51, 51, 51));
        mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        mainPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Product Management");
        mainPanel.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        BodyPanel.setBackground(new java.awt.Color(51, 51, 51));
        BodyPanel.setLayout(new java.awt.GridLayout(1, 2, 15, 0));

        formPanel.setBackground(new java.awt.Color(51, 51, 51));
        formPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        formPanel.setLayout(new java.awt.GridLayout(6, 2, 5, 5));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Product Name :");
        formPanel.add(jLabel2);
        formPanel.add(productNameField);

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Category :");
        formPanel.add(jLabel3);

        categoryCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Supplement", "Appareal", "Equipment", "Accessory", " " }));
        formPanel.add(categoryCombo);

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Price :");
        formPanel.add(jLabel4);
        formPanel.add(priceField);

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Stock Quantity :");
        formPanel.add(jLabel5);
        formPanel.add(stockField);

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Status :");
        formPanel.add(jLabel6);

        statusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Out of Stock", " " }));
        formPanel.add(statusCombo);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        jButton1.setBackground(new java.awt.Color(204, 51, 0));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1);

        jButton2.setBackground(new java.awt.Color(204, 51, 0));
        jButton2.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel1.add(jButton2);

        jButton3.setBackground(new java.awt.Color(204, 51, 0));
        jButton3.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Delete");
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel1.add(jButton3);

        formPanel.add(jPanel1);

        BodyPanel.add(formPanel);

        listPanel.setBackground(new java.awt.Color(51, 51, 51));
        listPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        listPanel.setLayout(new java.awt.BorderLayout());

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Product List :");
        listPanel.add(jLabel8, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));

        productTable.setBackground(new java.awt.Color(51, 51, 51));
        productTable.setForeground(new java.awt.Color(255, 255, 255));
        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Category", "Price", "Stock", "Status"
            }
        ));
        productTable.setGridColor(new java.awt.Color(255, 255, 255));
        productTable.setSelectionBackground(new java.awt.Color(204, 51, 0));
        productTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(productTable);

        listPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jButton4.setBackground(new java.awt.Color(204, 51, 0));
        jButton4.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Sort By Name");
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(this::jButton4ActionPerformed);
        jPanel2.add(jButton4);

        jButton5.setBackground(new java.awt.Color(204, 51, 0));
        jButton5.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Sort By Price");
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(this::jButton5ActionPerformed);
        jPanel2.add(jButton5);

        jButton6.setBackground(new java.awt.Color(204, 51, 0));
        jButton6.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Sort By Stock");
        jButton6.setBorderPainted(false);
        jButton6.addActionListener(this::jButton6ActionPerformed);
        jPanel2.add(jButton6);

        listPanel.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        BodyPanel.add(listPanel);

        mainPanel.add(BodyPanel, java.awt.BorderLayout.CENTER);

        add(mainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
        String name = productNameField.getText().trim();
        String category = categoryCombo.getSelectedItem().toString();
        String status = statusCombo.getSelectedItem().toString();

        double price = Double.parseDouble(priceField.getText().trim());
        int stock = Integer.parseInt(stockField.getText().trim());

        // Empty check
        if (name.isEmpty()) {
            throw new IllegalArgumentException("Product name is required");
        }

        // Alphabet-only name
        if (!name.matches("[a-zA-Z ]+")) {
            throw new IllegalArgumentException("Product name cannot contain numbers");
        }

        // Numeric validation
        if (price <= 0) {
            throw new IllegalArgumentException("Price must be greater than 0");
        }

        if (stock < 0) {
            throw new IllegalArgumentException("Stock cannot be negative");
        }

        // Create object
        Product product = new Product(name, category, price, stock, status);
        productList.add(product);

        // Add to table
        DefaultTableModel model =
                (DefaultTableModel) productTable.getModel();

        model.addRow(new Object[]{
            productList.size(),
            product.getProductName(),
            product.getCategory(),
            product.getPrice(),
            product.getStock(),
            product.getStatus()
        });

        // Clear form
        productNameField.setText("");
        priceField.setText("");
        stockField.setText("");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
                "Price and stock must be numeric",
                "Input Error",
                JOptionPane.ERROR_MESSAGE);

    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Input Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
int row = productTable.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this,
                "Please select a product to delete",
                "Delete Error",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    int modelRow = productTable.convertRowIndexToModel(row);

    productList.remove(modelRow);

    DefaultTableModel model =
            (DefaultTableModel) productTable.getModel();
    model.removeRow(modelRow);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 try {
        int row = productTable.getSelectedRow();
        if (row == -1) {
            throw new IllegalArgumentException("Select a product to update");
        }

        int modelRow = productTable.convertRowIndexToModel(row);

        String name = productNameField.getText().trim();
        String category = categoryCombo.getSelectedItem().toString();
        String status = statusCombo.getSelectedItem().toString();

        double price = Double.parseDouble(priceField.getText().trim());
        int stock = Integer.parseInt(stockField.getText().trim());

        if (!name.matches("[a-zA-Z ]+")) {
            throw new IllegalArgumentException("Invalid product name");
        }

        if (price <= 0 || stock < 0) {
            throw new IllegalArgumentException("Invalid price or stock value");
        }

        // Update object
        Product product = productList.get(modelRow);
        product.setProductName(name);
        product.setCategory(category);
        product.setPrice(price);
        product.setStock(stock);
        product.setStatus(status);

        // Update table
        DefaultTableModel model =
                (DefaultTableModel) productTable.getModel();

        model.setValueAt(product.getProductName(), modelRow, 0);
        model.setValueAt(product.getCategory(), modelRow, 1);
        model.setValueAt(product.getPrice(), modelRow, 2);
        model.setValueAt(product.getStock(), modelRow, 3);
        model.setValueAt(product.getStatus(), modelRow, 4);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
                "Price and stock must be numeric",
                "Update Error",
                JOptionPane.ERROR_MESSAGE);

    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Update Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
sorter.setSortKeys(
        List.of(
            new RowSorter.SortKey(
                0,                  // Product Name column
                SortOrder.ASCENDING
            )
        )
    );
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
sorter.setSortKeys(
        List.of(
            new RowSorter.SortKey(
                2,                  // Price column
                SortOrder.ASCENDING
            )
        )
    );
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
 sorter.setSortKeys(
        List.of(
            new RowSorter.SortKey(
                3,                  // Stock column
                SortOrder.ASCENDING
            )
        )
    );
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BodyPanel;
    private javax.swing.JComboBox<String> categoryCombo;
    private javax.swing.JPanel formPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel listPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField priceField;
    private javax.swing.JTextField productNameField;
    private javax.swing.JTable productTable;
    private javax.swing.JComboBox<String> statusCombo;
    private javax.swing.JTextField stockField;
    // End of variables declaration//GEN-END:variables
}
