/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.Session;
import Util.DataStore;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adhish
 */
public class SessionBookingPanel extends javax.swing.JPanel {
    private LinkedList<Session> sessionList;


    /**
     * Creates new form SessionBookingPanel
     */
    public SessionBookingPanel() {
        initComponents();
        sessionList = DataStore.sessions; 
        
        
        
        DefaultTableModel model =
        (DefaultTableModel) sessionTable.getModel();

for (Session s : sessionList) {
    model.addRow(new Object[]{
        model.getRowCount() + 1,
        s.getSessionName(),
        s.getTrainerName(),
        s.getSessionType(),
        s.getTime(),
        s.getCapacity()
    });
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sessionTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new java.awt.BorderLayout());

        mainPanel.setBackground(new java.awt.Color(51, 51, 51));
        mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        mainPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Book Sessions");
        mainPanel.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));

        sessionTable.setBackground(new java.awt.Color(51, 51, 51));
        sessionTable.setForeground(new java.awt.Color(255, 255, 255));
        sessionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Trainer", "Type", "Time", "Available Slots"
            }
        ));
        sessionTable.setGridColor(new java.awt.Color(255, 255, 255));
        sessionTable.setSelectionBackground(new java.awt.Color(204, 51, 0));
        sessionTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(sessionTable);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        mainPanel.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jButton1.setBackground(new java.awt.Color(204, 51, 0));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Book Session");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1);

        mainPanel.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        add(mainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
        int selectedRow = sessionTable.getSelectedRow();

        if (selectedRow == -1) {
            throw new IllegalArgumentException("Please select a session to book");
        }

        // Sorting-safe index
        int modelRow = sessionTable.convertRowIndexToModel(selectedRow);

        Session session = sessionList.get(modelRow);

        if (session.getCapacity() <= 0) {
            throw new IllegalArgumentException("No slots available for this session");
        }

        // Reduce capacity
        session.setCapacity(session.getCapacity() - 1);

        // Update table
        DefaultTableModel model =
                (DefaultTableModel) sessionTable.getModel();

        model.setValueAt(session.getCapacity(), modelRow, 5);

        JOptionPane.showMessageDialog(this,
                "Session booked successfully!",
                "Booking Confirmed",
                JOptionPane.INFORMATION_MESSAGE);

    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Booking Error",
                JOptionPane.ERROR_MESSAGE);
    }    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable sessionTable;
    // End of variables declaration//GEN-END:variables
}
