/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.Session;
import Util.DataStore;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import java.util.List;



/**
 *
 * @author adhish
 */
public class SessionManagementPanel extends javax.swing.JPanel {
    private LinkedList<Session> sessionList = new LinkedList<>();
    private TableRowSorter<DefaultTableModel> sorter;



    /**
     * Creates new form SessionManagementPanel
     */
    public SessionManagementPanel() {
        initComponents();
        loadSessionsToTable();   
        
        DefaultTableModel model =
        (DefaultTableModel) sessionTable.getModel();

sorter = new TableRowSorter<>(model);
sessionTable.setRowSorter(sorter);
    }
    
    private void loadSessionsToTable() {

    DefaultTableModel model =
            (DefaultTableModel) sessionTable.getModel();

    model.setRowCount(0); // clear table

    for (Session s : DataStore.sessions) {
        model.addRow(new Object[]{
            s.getSessionName(),
            s.getTrainerName(),
            s.getSessionType(),
            s.getTime(),
            s.getCapacity()
        });
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        formPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sessionNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        trainerField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sessionTypeCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        timeField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        capacityField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        listPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sessionTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new java.awt.BorderLayout());

        mainPanel.setBackground(new java.awt.Color(51, 51, 51));
        mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        mainPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Session Management");
        mainPanel.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new java.awt.GridLayout(1, 2, 15, 0));

        formPanel.setBackground(new java.awt.Color(51, 51, 51));
        formPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        formPanel.setLayout(new java.awt.GridLayout(6, 2));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Session Name:");
        formPanel.add(jLabel2);

        sessionNameField.addActionListener(this::sessionNameFieldActionPerformed);
        formPanel.add(sessionNameField);

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Trainer :");
        formPanel.add(jLabel3);

        trainerField.addActionListener(this::trainerFieldActionPerformed);
        formPanel.add(trainerField);

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Session Type:");
        formPanel.add(jLabel4);

        sessionTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yoga", "Cardio", "Strength", "Swimming", "Sports" }));
        formPanel.add(sessionTypeCombo);

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Time:");
        formPanel.add(jLabel5);

        timeField.addActionListener(this::timeFieldActionPerformed);
        formPanel.add(timeField);

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Capacity:");
        formPanel.add(jLabel6);

        capacityField.addActionListener(this::capacityFieldActionPerformed);
        formPanel.add(capacityField);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jButton1.setBackground(new java.awt.Color(204, 51, 0));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel2.add(jButton1);

        jButton2.setBackground(new java.awt.Color(204, 51, 0));
        jButton2.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel2.add(jButton2);

        jButton3.setBackground(new java.awt.Color(204, 51, 0));
        jButton3.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Delete");
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel2.add(jButton3);

        formPanel.add(jPanel2);

        jPanel1.add(formPanel);

        listPanel.setBackground(new java.awt.Color(51, 51, 51));
        listPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        listPanel.setLayout(new java.awt.BorderLayout());

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Session List :");
        listPanel.add(jLabel8, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));

        sessionTable.setBackground(new java.awt.Color(51, 51, 51));
        sessionTable.setForeground(new java.awt.Color(255, 255, 255));
        sessionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Trainer", "Type", "Time", "Capacity"
            }
        ));
        sessionTable.setSelectionBackground(new java.awt.Color(204, 51, 0));
        sessionTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(sessionTable);

        listPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jButton4.setBackground(new java.awt.Color(204, 51, 0));
        jButton4.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Sort By Name");
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(this::jButton4ActionPerformed);
        jPanel3.add(jButton4);

        jButton5.setBackground(new java.awt.Color(204, 51, 0));
        jButton5.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Sort By Capacity");
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(this::jButton5ActionPerformed);
        jPanel3.add(jButton5);

        listPanel.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(listPanel);

        mainPanel.add(jPanel1, java.awt.BorderLayout.CENTER);

        add(mainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void sessionNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sessionNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sessionNameFieldActionPerformed

    private void trainerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trainerFieldActionPerformed

    private void timeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeFieldActionPerformed

    private void capacityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capacityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_capacityFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
        String name = sessionNameField.getText().trim();
        String trainer = trainerField.getText().trim();
        String type = sessionTypeCombo.getSelectedItem().toString();
        String time = timeField.getText().trim();
        int capacity = Integer.parseInt(capacityField.getText().trim());

        // Empty check
        if (name.isEmpty() || trainer.isEmpty() || time.isEmpty()) {
            throw new IllegalArgumentException("All fields are required");
        }

        // Text-only validation
        if (!name.matches("[a-zA-Z ]+")) {
            throw new IllegalArgumentException("Session name cannot contain numbers");
        }

        if (!trainer.matches("[a-zA-Z ]+")) {
            throw new IllegalArgumentException("Trainer name cannot contain numbers");
        }

        // Capacity validation
        if (capacity <= 0) {
            throw new IllegalArgumentException("Capacity must be a positive number");
        }

        // Create object
        Session session = new Session(name, trainer, type, time, capacity);
        sessionList.add(session);

        // Add to table
        DefaultTableModel model =
                (DefaultTableModel) sessionTable.getModel();

        model.addRow(new Object[]{
            sessionList.size(),
            session.getSessionName(),
            session.getTrainerName(),
            session.getSessionType(),
            session.getTime(),
            session.getCapacity()
        });

        // Clear form
        sessionNameField.setText("");
        trainerField.setText("");
        timeField.setText("");
        capacityField.setText("");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
                "Capacity must be numeric",
                "Input Error",
                JOptionPane.ERROR_MESSAGE);

    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Input Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
int row = sessionTable.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this,
                "Please select a session to delete",
                "Delete Error",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    int modelRow = sessionTable.convertRowIndexToModel(row);

    sessionList.remove(modelRow);

    DefaultTableModel model =
            (DefaultTableModel) sessionTable.getModel();
    model.removeRow(modelRow);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try {
        int row = sessionTable.getSelectedRow();
        if (row == -1) {
            throw new IllegalArgumentException("Select a session to update");
        }

        int modelRow = sessionTable.convertRowIndexToModel(row);

        String name = sessionNameField.getText().trim();
        String trainer = trainerField.getText().trim();
        String type = sessionTypeCombo.getSelectedItem().toString();
        String time = timeField.getText().trim();
        int capacity = Integer.parseInt(capacityField.getText().trim());

        if (!name.matches("[a-zA-Z ]+")) {
            throw new IllegalArgumentException("Invalid session name");
        }

        if (!trainer.matches("[a-zA-Z ]+")) {
            throw new IllegalArgumentException("Invalid trainer name");
        }

        if (capacity <= 0) {
            throw new IllegalArgumentException("Capacity must be positive");
        }

        // Update object
        Session session = sessionList.get(modelRow);
        session.setSessionName(name);
        session.setTrainerName(trainer);
        session.setSessionType(type);
        session.setTime(time);
        session.setCapacity(capacity);

        // Update table
        DefaultTableModel model =
                (DefaultTableModel) sessionTable.getModel();

        model.setValueAt(session.getSessionName(), modelRow, 1);
        model.setValueAt(session.getTrainerName(), modelRow, 2);
        model.setValueAt(session.getSessionType(), modelRow, 3);
        model.setValueAt(session.getTime(), modelRow, 4);
        model.setValueAt(session.getCapacity(), modelRow, 5);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
                "Capacity must be numeric",
                "Update Error",
                JOptionPane.ERROR_MESSAGE);

    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Update Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
sorter.setSortKeys(
        List.of(
            new RowSorter.SortKey(
                0,                      // Session Name column
                SortOrder.ASCENDING
            )
        )
    );
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
sorter.setSortKeys(
        List.of(
            new RowSorter.SortKey(
                4,                      // Capacity column
                SortOrder.ASCENDING
            )
        )
    );
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField capacityField;
    private javax.swing.JPanel formPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel listPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField sessionNameField;
    private javax.swing.JTable sessionTable;
    private javax.swing.JComboBox<String> sessionTypeCombo;
    private javax.swing.JTextField timeField;
    private javax.swing.JTextField trainerField;
    // End of variables declaration//GEN-END:variables
}
