/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.Product;
import Util.DataStore;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adhish
 */
public class StorePanel extends javax.swing.JPanel {
    private LinkedList<Product> productList;


    /**
     * Creates new form StorePanel
     */
    public StorePanel() {
        initComponents();
        productList = DataStore.products;
        
        
         DefaultTableModel model =
            (DefaultTableModel) productTable.getModel();

    for (Product p : productList) {
        model.addRow(new Object[]{
            model.getRowCount() + 1,
            p.getProductName(),
            p.getCategory(),
            p.getPrice(),
            p.getStock()
        });
    }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new java.awt.BorderLayout());

        mainPanel.setBackground(new java.awt.Color(51, 51, 51));
        mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        mainPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gym Store");
        mainPanel.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));

        productTable.setBackground(new java.awt.Color(51, 51, 51));
        productTable.setForeground(new java.awt.Color(255, 255, 255));
        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Category", "Price", "Stock"
            }
        ));
        productTable.setGridColor(new java.awt.Color(255, 255, 255));
        productTable.setSelectionBackground(new java.awt.Color(204, 51, 0));
        productTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(productTable);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        mainPanel.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jButton1.setBackground(new java.awt.Color(204, 51, 0));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Buy");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel2.add(jButton1);

        mainPanel.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        add(mainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 try {
        int selectedRow = productTable.getSelectedRow();

        if (selectedRow == -1) {
            throw new IllegalArgumentException("Please select a product to buy");
        }

        // Sorting-safe index
        int modelRow = productTable.convertRowIndexToModel(selectedRow);

        Product product = productList.get(modelRow);

        if (product.getStock() <= 0) {
            throw new IllegalArgumentException("Product is out of stock");
        }

        // Confirm purchase
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Buy " + product.getProductName() + " for $" + product.getPrice() + "?",
                "Confirm Purchase",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        // Reduce stock
        product.setStock(product.getStock() - 1);

        // Update table
        DefaultTableModel model =
                (DefaultTableModel) productTable.getModel();

        model.setValueAt(product.getStock(), modelRow, 4);

        JOptionPane.showMessageDialog(this,
                "Purchase successful!",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);

    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Purchase Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable productTable;
    // End of variables declaration//GEN-END:variables
}
