/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.Workout;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author adhish
 */
public class WorkoutCheckInPanel extends javax.swing.JPanel {
    private LinkedList<Workout> workoutList = new LinkedList<>();


    /**
     * Creates new form WorkoutCheckInPlane
     */
    public WorkoutCheckInPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        formPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        exerciseCombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        durationField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        caloriesField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new java.awt.BorderLayout());

        mainPanel.setBackground(new java.awt.Color(51, 51, 51));
        mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        mainPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Workout Check-in");
        mainPanel.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        formPanel.setBackground(new java.awt.Color(51, 51, 51));
        formPanel.setLayout(new java.awt.GridLayout(6, 1));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Exercise :");
        formPanel.add(jLabel2);

        exerciseCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        formPanel.add(exerciseCombo);

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Duration:");
        formPanel.add(jLabel3);
        formPanel.add(durationField);

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Calories Burned :");
        formPanel.add(jLabel4);
        formPanel.add(caloriesField);

        mainPanel.add(formPanel, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jButton1.setBackground(new java.awt.Color(204, 51, 0));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Check In");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1);

        mainPanel.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        add(mainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
        String exercise = exerciseCombo.getSelectedItem().toString();
        int duration = Integer.parseInt(durationField.getText().trim());
        int calories = Integer.parseInt(caloriesField.getText().trim());

        // Validation
        if (duration <= 0) {
            throw new IllegalArgumentException("Duration must be a positive number");
        }

        if (calories <= 0) {
            throw new IllegalArgumentException("Calories must be a positive number");
        }

        // Create workout record
        Workout workout = new Workout(exercise, duration, calories);
        workoutList.add(workout);

        // Clear fields
        durationField.setText("");
        caloriesField.setText("");

        JOptionPane.showMessageDialog(this,
                "Workout checked in successfully!",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
                "Duration and calories must be numeric",
                "Input Error",
                JOptionPane.ERROR_MESSAGE);

    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Input Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField caloriesField;
    private javax.swing.JTextField durationField;
    private javax.swing.JComboBox<String> exerciseCombo;
    private javax.swing.JPanel formPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
